services:
  # Dockerhub
  #   https://hub.docker.com/_/postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: metabase
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U metabase -d metabase" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Dockerhub
  #   https://hub.docker.com/r/metabase/metabase
  metabase:
    image: metabase/metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
    ports:
      - 3000:3000
    volumes:
      - ./plugins:/plugins
    healthcheck:
      test: [ "CMD-SHELL", "curl http://0.0.0.0:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Dockerhub:
  #   https://hub.docker.com/r/yandex/clickhouse-server/
  # Notes:
  #   Container exposes 8123 port for HTTP interface and 9000 port for native client.
  clickhouse:
    image: yandex/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD-SHELL", "curl http://0.0.0.0:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:
